### ISSUE TITLE
Add Kibana Data view support

### ISSUE THREAD

**Issue by xco-sk** [xco-sk/eck-custom-resources#39]
As per user request, we should add support for Kibana Data view resource type as a possible future replacement for index patterns.

API Docs: https://www.elastic.co/guide/en/kibana/current/data-views-api.html

**Comment by codeeong** [comment]
Hi, is there a release for this feature coming soon? I am looking to using this operator for creation of kibana data views with ES8, thank you!

**Comment by xco-sk** [comment]
Hi @codeeong, I just opened PR that merges DataView support into the master. I want to give it a last round of testing and then release a new version of the operator.

**Comment by xco-sk** [comment]
New operator and chart released. Just a side note, if you already have the operator installed using the helm chart, you will probably have to install new data view CRD manually, see upgrade [instructions in the readme](https://github.com/xco-sk/eck-custom-resources#from-032-to-041). Usage and sample of DataView CRD are documented [here](https://github.com/xco-sk/eck-custom-resources/blob/main/docs/cr_data_view.md).

**Comment by codeeong** [comment]
hi @xco-sk , thank you so much for releasing the new version, looking forward to using it!
