### ISSUE TITLE
Helm Chart: Connection test fails

### ISSUE THREAD

**Issue by acm-073** [xco-sk/eck-custom-resources#42]
Hello,

we use the helm chart to deploy eck-custom-resources, which we find a very helpful piece of software.

However, the connection test in the helm chart has two issues:
- it should only be enabled if Values.metrics.enabled is true, because otherwise the service that is being tested will not be deployed
- currently the test makes a request to `<service>:8080` which returns a 404. It should rather call `<service>:8080/metrics` which would return a success HTTP status code.

Would be glad to see these things fixed, because it's quite annoying to have the failed test pod causing an alert each time we deploy the application.

Thanks!
Best regards
Albrecht

**Comment by xco-sk** [comment]
Hi @acm-073, thanks for reporting, I will take a look and fix it as soon as possible.

**Comment by xco-sk** [comment]
> Just tested, works fine!
> 
> Thanks a lot!

Great to hear that. Thanks again for reporting.
