### ISSUE TITLE
Feature request: component template

### ISSUE THREAD

**Issue by an-tex** [xco-sk/eck-custom-resources#55]
it's very similar to the index template but lives under it's own path `/_component_template/...` 

tbh i haven't tried out this controller yet but it looks great already :) i was waiting for elastic to release StackConfigPolicy so i can finally get rid of my kubernetes jobs to do all this and now it's an enterprise feature... well i guess i'll migrate to this project soon enough. thanks!

**Comment by xco-sk** [comment]
Wil definitely take a look and keep you posted, thanks for the suggestion :-).
