### ISSUE TITLE
Feature request: Service Account mechanism

### ISSUE THREAD

**Issue by husnialhamdani** [xco-sk/eck-custom-resources#61]
Hi, 

Can we use Service Account mechanism instead of Basic authentication?
https://www.elastic.co/guide/en/elasticsearch/reference/current/service-accounts.html

Thanks

**Comment by xco-sk** [comment]
Hi @husnialhamdani, thanks for the suggestion. Honestly, I did not even know about service account support in ES so thanks for pointing that out too :-).
However, my understanding after reading the docs, is, that there are only 3 built-in service accounts, that should be used for 3 very specific cases:
1. Fleet server - ES authentication
2. Kibana - ES authentication
3. Enterprise search - ES authentication

From that, it seems like the ECK-CR operator authentication with ES won't work (or maybe it will but should not be used?), or did I misunderstand the usage of service accounts?
